In [1]:
import numpy as np

In [2]:
a = np.array([1,4,0,2,3,8,9,7], float)
a > 3

array([False,  True, False, False, False,  True,  True,  True])

In [3]:
a[a>3]

array([4., 8., 9., 7.])

In [4]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int)   # 반드시 integer로 선언
a[b]      # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출

array([2., 2., 4., 8., 6., 4.])